### ISSUE TITLE
This is wonderful 💫️ 🤩️

### ISSUE THREAD

**Issue by Syaw0** [reymon359/how-to-live#10]
Hello my good friend, I found this repo by accident and I really liked the idea and it attracted me a lot. I will definitely work on this repo in the future.
I wanted to thank you for the open source of this project.😬️💜️

**Comment by reymon359** [comment]
Hey there @Syaw0 

Thanks for your kind words and for showing interest in the project. If you have any questions or need any help, just let me know. I'm here to help. :)
